### ISSUE TITLE
Wrong XX pattern

### ISSUE THREAD

**Issue by mimoo** [flynn/noise#17]
Hello,

Looking at the XX pattern [here](https://github.com/flynn/noise/blob/master/patterns.go#L96)

```go
var HandshakeXX = HandshakePattern{
	Name: "XX",
	Messages: [][]MessagePattern{
		{MessagePatternE},
		{MessagePatternE, MessagePatternDHEE, MessagePatternS, MessagePatternDHSE},
		{MessagePatternS, MessagePatternDHSE},
	},
}
```

The second message pattern is incorrect, it should end with `MessagePatternDHES` instead as seen [here](http://noiseprotocol.org/noise.html#interactive-patterns)

**Comment by titanous** [comment]
This was explained in #19, I'll leave the open and close this issue.
