### ISSUE TITLE
Add noise pipes

### ISSUE THREAD

**Issue by Scratch-net** [flynn/noise#6]
Hi and thanks for this nice implementation!
I'm working on noiseTLS project https://github.com/go-noisetls/noisetls and would like to use noise pipes for that. Will you find some time to implement it?

**Comment by titanous** [comment]
I don't currently have time to implement it, but I'd be happy to review if you want to start sending pull requests.

**Comment by Scratch-net** [comment]
Ok, maybe we'll figure something out
