### ISSUE TITLE
Expose some cipher.AEAD functions in Cipher

### ISSUE THREAD

**Issue by cretz** [flynn/noise#8]
Can you make the `Cipher` interface (or the `CipherFunc` iface) at least expose `NonceSize` and `Overhead` from `cipher.AEAD`?

**Comment by titanous** [comment]
The nonce is always 8 bytes in Noise, I'm not sure what you're looking for?

**Comment by cretz** [comment]
I have two `CipherState`s and am making a streaming enc/dec connection, so I guess I really just need the overhead to determine some block sizes...but I suppose it is not important.

**Comment by titanous** [comment]
Feel free to send a PR if you have a concrete suggestion of what you want, happy to review there.
